[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']
nixLibs = ['php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
APP_ENV = 'production'
