[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18', 'nginx']
nixLibs = ['php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.iconv', 'php82Extensions.intl', 'php82Extensions.bcmath', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.gd']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
    'cp .env.example .env',
    'php artisan key:generate',
    'npm ci',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[phases.setup.nixPkgs]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
NODE_ENV = 'production'
APP_ENV = 'production'
